import { FormEvent, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { BadgePercent, Building2, CheckCircle2, CircleOff, Clock, Gift, Hourglass, Pencil, Plus, Printer } from 'lucide-react'
import client, { errorMessage } from '../../api/client'
import { Dialog, Empty, ErrorBox, Loading, PageHeader } from '../../components/UI'
import { StatTile } from '../portals/widgets'
import { day, money, paymentLabel, period, printReceipt, StatusTag, type Payment, type Plan, type Subscription } from './shared'

type Offer = { id: string, name: string, code: string | null, description: string, discountType: string, discountValue: number, currency: string, startsAt: string, endsAt: string, status: string, state: string, planIds: string[], schoolIds: string[], newCustomersOnly: boolean, maxUses: number | null, used: number }
type Banner = { id: string, title: string, message: string, ctaLabel: string, ctaUrl: string, placement: string, enabled: boolean, startsAt: string, endsAt: string }
type Overview = { schools: number, active: number, trials: number, complimentary: number, grace: number, expired: number, cancelled: number, none: number, expiringSoon: number, activeOffers: number, revenue: { currency: string, payments: number, total: number }[], audit: { id: string, action: string, actorRole: string, createdAt: string, schoolName: string | null }[] }
type Settings = { graceDays: number, paymentsEnabled: boolean, webhookConfigured: boolean, testMode: boolean }
type Open = { kind: 'plan', item?: Plan } | { kind: 'offer', item?: Offer } | { kind: 'banner', item?: Banner } | { kind: 'manage' | 'price', item: Subscription }
const tabs = [['overview', 'Overview'], ['plans', 'Plans'], ['offers', 'Offers & promotions'], ['subscriptions', 'Subscriptions'], ['payments', 'Payments & receipts'], ['settings', 'Settings']] as const
const placements: Record<string, string> = { login: 'Sign-in page', pricing: 'Plans list', 'admin-dashboard': 'School administrator dashboard', subscription: 'Subscription page' }
const actions: Record<string, string> = { complimentary: 'Grant complimentary access', trial: 'Start a trial', activate: 'Activate without online payment', extend: 'Extend the end date', 'change-plan': 'Change plan', cancel: 'Cancel subscription', restore: 'Restore cancelled subscription' }
const confirmations: Record<string, string> = { complimentary: 'Grant complimentary access to ', activate: 'Activate a subscription without payment for ', cancel: 'Cancel the subscription of ', 'change-plan': 'Change the plan of ' }
const local = (iso?: string) => { const d = iso ? new Date(iso) : new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
const utc = (value: FormDataEntryValue | null) => new Date(String(value)).toISOString()
const minor = (value: FormDataEntryValue | null) => Math.round(Number(value) * 100)
const discount = (o: Offer) => o.discountType === 'percent' ? o.discountValue + '%' : money(o.discountValue, o.currency)

// Platform billing. Every figure is read from /billing/*; prices are stored and calculated by the server.
export default function BillingPage() {
  const { tab = 'overview' } = useParams(), cache = useQueryClient()
  const [open, setOpen] = useState<Open | null>(null), [action, setAction] = useState('complimentary')
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('')
  const load = <T,>(key: string, enabled = true) => useQuery<T>({ queryKey: ['billing', key], enabled, queryFn: async () => (await client.get('/billing/' + key)).data.data })
  const overview = load<Overview>('overview', tab === 'overview'), plans = load<Plan[]>('plans'), offers = load<Offer[]>('offers', tab === 'offers'), banners = load<Banner[]>('banners', tab === 'offers')
  const subscriptions = load<Subscription[]>('subscriptions', tab === 'subscriptions' || tab === 'offers'), payments = load<Payment[]>('payments', tab === 'payments'), settings = load<Settings>('settings', tab === 'settings')
  async function run(task: () => Promise<string>) { setBusy(true); setError(''); try { setMessage(await task()); setOpen(null); await cache.invalidateQueries({ queryKey: ['billing'] }) } catch (e) { setError(errorMessage(e)) } finally { setBusy(false) } }
  const show = (next: Open) => { setError(''); setMessage(''); setAction('complimentary'); setOpen(next) }
  const save = (path: string, id: string | undefined, body: unknown, done: string) => run(async () => { await (id ? client.put(path + '/' + id, body) : client.post(path, body)); return done })
  function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const f = new FormData(e.currentTarget), o = open!
    if (o.kind === 'plan') return save('/billing/plans', o.item?.id, { name: f.get('name'), description: f.get('description'), status: f.get('status'), billingPeriod: f.get('billingPeriod'), basePrice: minor(f.get('price')), currency: f.get('currency'), trialDays: Number(f.get('trialDays')), features: String(f.get('features')).split('\n'), displayOrder: Number(f.get('displayOrder')), highlighted: f.get('highlighted') === 'on' }, 'Plan saved.')
    if (o.kind === 'offer') return save('/billing/offers', o.item?.id, { name: f.get('name'), code: f.get('code') || null, description: f.get('description'), discountType: f.get('discountType'), discountValue: f.get('discountType') === 'percent' ? Number(f.get('value')) : minor(f.get('value')), currency: f.get('currency'), startsAt: utc(f.get('startsAt')), endsAt: utc(f.get('endsAt')), status: f.get('status'), planIds: f.getAll('planIds'), schoolIds: f.getAll('schoolIds'), newCustomersOnly: f.get('newCustomersOnly') === 'on', maxUses: f.get('maxUses') ? Number(f.get('maxUses')) : null }, 'Offer saved.')
    if (o.kind === 'banner') return save('/billing/banners', o.item?.id, { title: f.get('title'), message: f.get('message'), ctaLabel: f.get('ctaLabel'), ctaUrl: f.get('ctaUrl'), placement: f.get('placement'), enabled: f.get('enabled') === 'on', startsAt: utc(f.get('startsAt')), endsAt: utc(f.get('endsAt')) }, 'Promotion saved.')
    if (o.kind === 'price') {
      if (!window.confirm('Change the price for ' + o.item.schoolName + '? This overrides the plan price for this school and is recorded in the audit log.')) return
      return run(async () => (await client.put('/billing/schools/' + o.item.schoolId + '/prices/' + f.get('planId'), { price: f.get('price') === '' ? null : minor(f.get('price')), note: f.get('note') })).data.message)
    }
    if (confirmations[action] && !window.confirm(confirmations[action] + o.item.schoolName + '? This is recorded in the audit log.')) return
    run(async () => (await client.post('/billing/schools/' + o.item.schoolId + '/subscription', { action, planId: f.get('planId') || null, days: f.get('days') ? Number(f.get('days')) : null, note: f.get('note') })).data.message)
  }
  const planOptions = plans.data?.map(p => <option key={p.id} value={p.id}>{p.name} · {money(p.basePrice, p.currency)}/{period[p.billingPeriod]}</option>)
  const o = overview.data, st = settings.data
  return <><PageHeader eyebrow="SUPER ADMIN PORTAL" title="Billing & subscriptions" description="Plans, pricing, offers, school subscriptions and payments. Access can always be granted without a payment." />
    <nav className="module-tabs" aria-label="Billing">{tabs.map(([key, label]) => <Link key={key} className={tab === key ? 'selected' : ''} to={'/super-admin/billing/' + key} onClick={() => { setError(''); setMessage('') }}>{label}</Link>)}</nav>
    {error && !open && <ErrorBox message={error} />} {message && <div className="success-box" role="status">{message}</div>}

    {tab === 'overview' && (overview.isError ? <ErrorBox message={errorMessage(overview.error)} /> : overview.isPending ? <Loading /> : <>
      <div className="stats-grid"><StatTile label="Active subscriptions" value={o!.active} note={o!.schools + ' schools on the platform'} icon={CheckCircle2} tone="teal" to="/super-admin/billing/subscriptions" /><StatTile label="Trials" value={o!.trials} note="Schools evaluating EduOS" icon={Hourglass} tone="blue" /><StatTile label="Complimentary" value={o!.complimentary} note="Access granted by the platform" icon={Gift} tone="purple" /><StatTile label="Expiring in 30 days" value={o!.expiringSoon} note="Trials and subscriptions" icon={Clock} tone="peach" /></div>
      <div className="stats-grid"><StatTile label="In grace period" value={o!.grace} note="Ended, still within grace" icon={Clock} tone="peach" /><StatTile label="Expired" value={o!.expired} note="School data is kept" icon={CircleOff} tone="peach" /><StatTile label="No subscription" value={o!.none} note="Not yet assigned a plan" icon={Building2} tone="blue" /><StatTile label="Active offers" value={o!.activeOffers} note="Running right now" icon={BadgePercent} tone="teal" to="/super-admin/billing/offers" /></div>
      <div className="dashboard-grid"><section className="panel" style={{ padding: 24 }}><h2>Verified payments</h2>{o!.revenue.length ? <div className="table-scroll"><table><thead><tr><th>Currency</th><th>Payments</th><th>Total received</th></tr></thead><tbody>{o!.revenue.map(r => <tr key={r.currency}><td>{r.currency}</td><td>{r.payments}</td><td>{money(r.total, r.currency)}</td></tr>)}</tbody></table></div> : <p className="muted">No verified payments yet.</p>}</section>
        <section className="panel" style={{ padding: 24 }}><h2>Recent billing activity</h2>{o!.audit.length ? <ul className="dash-list">{o!.audit.map(a => <li key={a.id}><div><strong>{a.action.replace('billing.', '').replace(/[._]/g, ' ')}</strong><small>{a.schoolName || 'Platform'} · {a.actorRole} · {new Date(a.createdAt).toLocaleString('en-IN')}</small></div></li>)}</ul> : <p className="muted">No billing changes recorded yet.</p>}</section></div></>)}

    {tab === 'plans' && <section className="panel" style={{ padding: 20 }}><div className="toolbar-actions"><button className="button primary" onClick={() => show({ kind: 'plan' })}><Plus size={17} />Create plan</button></div>
      {plans.isError ? <ErrorBox message={errorMessage(plans.error)} /> : plans.isPending ? <Loading /> : !plans.data.length ? <Empty title="No plans yet" description="Create the first plan schools can subscribe to." /> : <div className="table-scroll"><table><thead><tr><th>Plan</th><th>Price</th><th>Trial</th><th>Status</th><th>Order</th><th className="align-right">Actions</th></tr></thead><tbody>{plans.data.map(p => <tr key={p.id}>
        <td><strong>{p.name}</strong>{p.highlighted && <span className="status-tag active"> Recommended</span>}<small className="cell-small">{p.description || p.features.join(' · ')}</small></td><td>{money(p.basePrice, p.currency)} / {period[p.billingPeriod]}</td><td>{p.trialDays ? p.trialDays + ' days' : '—'}</td><td><StatusTag status={p.status} /></td><td>{p.displayOrder}</td>
        <td><div className="row-actions"><button className="icon-button" aria-label={'Edit ' + p.name} onClick={() => show({ kind: 'plan', item: p })}><Pencil size={16} /></button></div></td></tr>)}</tbody></table></div>}</section>}

    {tab === 'offers' && <><section className="panel" style={{ padding: 20, marginBottom: 20 }}><div className="toolbar-actions"><h2>Offers</h2><button className="button primary" onClick={() => show({ kind: 'offer' })}><Plus size={17} />Create offer</button></div><p className="muted">An offer with a code is a coupon the school enters. An offer without a code is applied automatically while it is active.</p>
      {offers.isError ? <ErrorBox message={errorMessage(offers.error)} /> : offers.isPending ? <Loading /> : !offers.data.length ? <Empty title="No offers yet" description="Create a coupon or an automatic sale." /> : <div className="table-scroll"><table><thead><tr><th>Offer</th><th>Code</th><th>Discount</th><th>Valid</th><th>Applies to</th><th>Used</th><th>Status</th><th className="align-right">Actions</th></tr></thead><tbody>{offers.data.map(x => <tr key={x.id}>
        <td><strong>{x.name}</strong><small className="cell-small">{x.description}</small></td><td>{x.code || 'Automatic'}</td><td>{discount(x)}</td><td>{day(x.startsAt)} – {day(x.endsAt)}</td><td>{x.planIds.length ? x.planIds.length + ' plan(s)' : 'All plans'} · {x.schoolIds.length ? x.schoolIds.length + ' school(s)' : 'All schools'}{x.newCustomersOnly ? ' · new customers' : ''}</td><td>{x.used}{x.maxUses ? ' / ' + x.maxUses : ''}</td><td><StatusTag status={x.state} /></td>
        <td><div className="row-actions"><button className="icon-button" aria-label={'Edit ' + x.name} onClick={() => show({ kind: 'offer', item: x })}><Pencil size={16} /></button></div></td></tr>)}</tbody></table></div>}</section>
      <section className="panel" style={{ padding: 20 }}><div className="toolbar-actions"><h2>Promotion banners</h2><button className="button primary" onClick={() => show({ kind: 'banner' })}><Plus size={17} />Create promotion</button></div><p className="muted">Shown only where you choose, and only between the start and end. Teachers, parents and students never see them.</p>
        {banners.isError ? <ErrorBox message={errorMessage(banners.error)} /> : banners.isPending ? <Loading /> : !banners.data.length ? <Empty title="No promotions yet" description="Nothing is shown to schools until you create and enable one." /> : <div className="table-scroll"><table><thead><tr><th>Promotion</th><th>Shown on</th><th>Valid</th><th>Status</th><th className="align-right">Actions</th></tr></thead><tbody>{banners.data.map(b => <tr key={b.id}>
          <td><strong>{b.title}</strong><small className="cell-small">{b.message}</small></td><td>{placements[b.placement]}</td><td>{day(b.startsAt)} – {day(b.endsAt)}</td><td><StatusTag status={!b.enabled ? 'Disabled' : new Date(b.startsAt) > new Date() ? 'Scheduled' : new Date(b.endsAt) <= new Date() ? 'Expired' : 'Active'} /></td>
          <td><div className="row-actions"><button className="icon-button" aria-label={'Edit ' + b.title} onClick={() => show({ kind: 'banner', item: b })}><Pencil size={16} /></button></div></td></tr>)}</tbody></table></div>}</section></>}

    {tab === 'subscriptions' && <section className="panel" style={{ padding: 20 }}>{subscriptions.isError ? <ErrorBox message={errorMessage(subscriptions.error)} /> : subscriptions.isPending ? <Loading /> : !subscriptions.data.length ? <Empty title="No schools yet" description="Onboard a school first." /> : <div className="table-scroll"><table><thead><tr><th>School</th><th>Plan</th><th>Status</th><th>Ends</th><th>Price</th><th>School price</th><th className="align-right">Actions</th></tr></thead><tbody>{subscriptions.data.map(s => <tr key={s.schoolId}>
      <td><strong>{s.schoolName}</strong><small className="cell-small">{s.note || (s.schoolActive ? '' : 'School deactivated')}</small></td><td>{s.planName || '—'}</td><td><StatusTag status={s.effectiveStatus} /></td><td>{s.status && !s.endsAt ? 'No end date' : day(s.endsAt)}</td><td>{s.status ? money(s.finalAmount, s.currency) : '—'}<small className="cell-small">{s.paymentState === 'Paid' ? 'Paid online' : s.status ? 'No payment required' : ''}</small></td>
      <td>{s.overrides?.length ? s.overrides.map(v => <small className="cell-small" key={v.planId}>{plans.data?.find(p => p.id === v.planId)?.name}: {money(v.price, plans.data?.find(p => p.id === v.planId)?.currency)}</small>) : 'Plan price'}</td>
      <td><div className="row-actions"><button className="button small secondary" aria-label={'Manage ' + s.schoolName} onClick={() => show({ kind: 'manage', item: s })}>Manage</button><button className="button small secondary" aria-label={'Set price for ' + s.schoolName} onClick={() => show({ kind: 'price', item: s })}>Set price</button></div></td></tr>)}</tbody></table></div>}</section>}

    {tab === 'payments' && <section className="panel" style={{ padding: 20 }}>{payments.isError ? <ErrorBox message={errorMessage(payments.error)} /> : payments.isPending ? <Loading /> : !payments.data.length ? <Empty title="No payments yet" description="Payments appear here once a school pays online." /> : <div className="table-scroll"><table><thead><tr><th>Date</th><th>School</th><th>Plan</th><th>Amount</th><th>Status</th><th>Order</th><th>Payment</th><th className="align-right">Receipt</th></tr></thead><tbody>{payments.data.map(p => <tr key={p.id}>
      <td>{day(p.createdAt)}</td><td>{p.schoolName}</td><td>{p.planName}</td><td>{money(p.amount, p.currency)}{p.discount > 0 && <small className="cell-small">{money(p.discount, p.currency)} discount</small>}</td><td><StatusTag status={paymentLabel(p.status)} />{p.failureReason && <small className="cell-small">{p.failureReason}</small>}</td><td>{p.providerOrderId}</td><td>{p.providerPaymentId || '—'}</td>
      <td className="align-right">{p.status === 'Paid' ? <button className="button small secondary" onClick={() => printReceipt(p)}><Printer size={14} />EDUOS-{String(p.receiptNo).padStart(6, '0')}</button> : '—'}</td></tr>)}</tbody></table></div>}</section>}

    {tab === 'settings' && (settings.isError ? <ErrorBox message={errorMessage(settings.error)} /> : settings.isPending ? <Loading /> : <><section className="panel" style={{ padding: 24, marginBottom: 20 }}><h2>Grace period</h2><p className="muted">After a subscription ends the school keeps working and sees a reminder. Nothing is deleted or locked when the period ends.</p>
      <form className="toolbar-actions" onSubmit={e => { e.preventDefault(); const days = Number(new FormData(e.currentTarget).get('graceDays')); run(async () => (await client.put('/billing/settings', { graceDays: days })).data.message) }}><label>Grace period (days)<input name="graceDays" type="number" min={0} max={90} required defaultValue={st!.graceDays} /></label><button className="button primary" disabled={busy}>Save</button></form></section>
      <section className="panel" style={{ padding: 24 }}><h2>Online payment</h2><dl className="record-details"><div><dt>Provider</dt><dd>Razorpay</dd></div><div><dt>Status</dt><dd>{st!.paymentsEnabled ? (st!.testMode ? 'Enabled · test mode' : 'Enabled · live') : 'Not configured'}</dd></div><div><dt>Webhook secret</dt><dd>{st!.webhookConfigured ? 'Configured' : 'Not configured'}</dd></div><div><dt>Webhook address</dt><dd>{window.location.origin}/api/v1/billing/webhooks/razorpay</dd></div></dl>
        <p className="muted">Keys are read from the server environment (RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET, RAZORPAY_WEBHOOK_SECRET) and are never shown here. Without keys, schools cannot pay online; trial, complimentary and manual access still work.</p></section></>)}

    {open && <Dialog title={open.kind === 'plan' ? (open.item ? 'Edit ' + open.item.name : 'Create plan') : open.kind === 'offer' ? (open.item ? 'Edit ' + open.item.name : 'Create offer') : open.kind === 'banner' ? (open.item ? 'Edit promotion' : 'Create promotion') : open.kind === 'price' ? 'School price · ' + open.item.schoolName : 'Manage subscription · ' + open.item.schoolName} onClose={() => !busy && setOpen(null)}><form onSubmit={submit}>{error && <ErrorBox message={error} />}
      {open.kind === 'plan' && <div className="form-grid"><label>Plan name<input name="name" required maxLength={100} defaultValue={open.item?.name} /></label><label>Status<select name="status" defaultValue={open.item?.status || 'Active'}><option>Active</option><option>Disabled</option></select></label>
        <label>Base price<input name="price" type="number" min={0} step="0.01" required defaultValue={open.item ? open.item.basePrice / 100 : ''} /></label><label>Currency<input name="currency" required minLength={3} maxLength={3} defaultValue={open.item?.currency || 'INR'} /></label>
        <label>Billing period<select name="billingPeriod" defaultValue={open.item?.billingPeriod || 'yearly'}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label><label>Trial days<input name="trialDays" type="number" min={0} max={365} required defaultValue={open.item?.trialDays ?? 0} /></label>
        <label>Display order<input name="displayOrder" type="number" min={0} max={1000} required defaultValue={open.item?.displayOrder ?? 0} /></label><label><span><input name="highlighted" type="checkbox" defaultChecked={open.item?.highlighted} /> Recommended plan</span></label>
        <label className="full-width">Description<input name="description" maxLength={1000} defaultValue={open.item?.description} /></label><label className="full-width">Included features<span className="optional"> (one per line)</span><textarea name="features" rows={4} defaultValue={open.item?.features.join('\n')} /></label></div>}
      {open.kind === 'offer' && <div className="form-grid"><label>Offer name<input name="name" required maxLength={100} defaultValue={open.item?.name} /></label><label>Offer code<span className="optional"> (empty = automatic)</span><input name="code" maxLength={40} pattern="[A-Za-z0-9_\-]{3,40}" defaultValue={open.item?.code || ''} autoComplete="off" /></label>
        <label>Discount type<select name="discountType" defaultValue={open.item?.discountType || 'percent'}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Discount value<input name="value" type="number" min={0.01} step="0.01" required defaultValue={open.item ? (open.item.discountType === 'percent' ? open.item.discountValue : open.item.discountValue / 100) : ''} /><small>Percent (1–100) or an amount.</small></label>
        <label>Starts<input name="startsAt" type="datetime-local" required defaultValue={local(open.item?.startsAt)} /></label><label>Ends<input name="endsAt" type="datetime-local" required defaultValue={open.item ? local(open.item.endsAt) : ''} /></label>
        <label>Status<select name="status" defaultValue={open.item?.status || 'Draft'}><option>Draft</option><option>Active</option><option>Disabled</option></select></label><label>Currency<input name="currency" required minLength={3} maxLength={3} defaultValue={open.item?.currency || 'INR'} /></label>
        <label>Plans<span className="optional"> (none = all)</span><select name="planIds" multiple defaultValue={open.item?.planIds}>{plans.data?.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Schools<span className="optional"> (none = all)</span><select name="schoolIds" multiple defaultValue={open.item?.schoolIds}>{subscriptions.data?.map(s => <option key={s.schoolId} value={s.schoolId}>{s.schoolName}</option>)}</select></label>
        <label>Maximum uses<span className="optional"> (optional)</span><input name="maxUses" type="number" min={1} defaultValue={open.item?.maxUses ?? ''} /></label><label><span><input name="newCustomersOnly" type="checkbox" defaultChecked={open.item?.newCustomersOnly} /> New customers only</span></label>
        <label className="full-width">Description<input name="description" maxLength={1000} defaultValue={open.item?.description} /></label></div>}
      {open.kind === 'banner' && <div className="form-grid"><label className="full-width">Title<input name="title" required maxLength={120} defaultValue={open.item?.title} /></label><label className="full-width">Message<input name="message" maxLength={500} defaultValue={open.item?.message} /></label>
        <label>Button text<span className="optional"> (optional)</span><input name="ctaLabel" maxLength={60} defaultValue={open.item?.ctaLabel} /></label><label>Button link<span className="optional"> (a page such as /subscription)</span><input name="ctaUrl" maxLength={300} pattern="/.*" defaultValue={open.item?.ctaUrl} /></label>
        <label>Shown on<select name="placement" defaultValue={open.item?.placement || 'subscription'}>{Object.entries(placements).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label><span><input name="enabled" type="checkbox" defaultChecked={open.item?.enabled} /> Enabled</span></label>
        <label>Starts<input name="startsAt" type="datetime-local" required defaultValue={local(open.item?.startsAt)} /></label><label>Ends<input name="endsAt" type="datetime-local" required defaultValue={open.item ? local(open.item.endsAt) : ''} /></label></div>}
      {open.kind === 'price' && <div className="form-stack"><label>Plan<select name="planId" required>{planOptions}</select></label><label>Price for this school<span className="optional"> (0 = free; empty = use the plan price)</span><input name="price" type="number" min={0} step="0.01" /></label><label>Reason<input name="note" maxLength={500} /></label></div>}
      {open.kind === 'manage' && <div className="form-stack"><p className="muted">Current: {open.item.planName || 'no plan'} · {open.item.effectiveStatus === 'None' ? 'no subscription' : open.item.effectiveStatus}{open.item.endsAt ? ' · ends ' + day(open.item.endsAt) : ''}</p>
        <label>Action<select value={action} onChange={e => setAction(e.target.value)}>{Object.entries(actions).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
        {['complimentary', 'trial', 'activate', 'change-plan'].includes(action) && <label>Plan{action === 'complimentary' && <span className="optional"> (optional)</span>}<select name="planId" required={action !== 'complimentary'} defaultValue={open.item.planId || ''}><option value="">{action === 'complimentary' ? 'Keep current plan' : 'Select a plan'}</option>{planOptions}</select></label>}
        {['complimentary', 'trial', 'extend'].includes(action) && <label>Days{action !== 'extend' && <span className="optional"> ({action === 'trial' ? 'empty = the plan’s trial length' : 'empty = no end date'})</span>}<input name="days" type="number" min={1} max={3650} required={action === 'extend'} /></label>}
        <label>Note<span className="optional"> (optional)</span><input name="note" maxLength={500} /></label></div>}
      <div className="modal-footer"><button type="button" className="button secondary" disabled={busy} onClick={() => setOpen(null)}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : open.kind === 'manage' ? 'Apply' : 'Save'}</button></div></form></Dialog>}</>
}
