import { FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Printer, FileDown, Save, Upload, Send } from 'lucide-react'
import Papa from 'papaparse'
import client,{errorMessage} from '../../api/client'
import { useAuthStore } from '../../store/auth'
import { Dialog, Empty, ErrorBox, Loading, PageHeader, today } from '../../components/UI'
import {data,Options,Row,workbook,printSchoolDocument} from './helpers'
const isAdmin=(role:string|undefined)=>role==='SuperAdmin'||role==='Principal'
export function FeesPage(){
 const admin=isAdmin(useAuthStore(s=>s.user?.roles[0])),cache=useQueryClient()
 const [modal,setModal]=useState<'charge'|Row|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[key,setKey]=useState('')
 const fees=useQuery<Row[]>({queryKey:['suite','fees'],queryFn:()=>data('/fees')}),payments=useQuery<Row[]>({queryKey:['suite','payments'],queryFn:()=>data('/fees/payments')})
 const options=useQuery<Options>({queryKey:['suite','options'],queryFn:()=>data('/options')})
 async function save(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setError('');const values=Object.fromEntries(new FormData(e.currentTarget))
  if(modal!=='charge'&&!window.confirm('Record '+values.amount+' '+(modal?.currency||'')+' received by '+values.method+'? This saves a permanent receipt and does not collect money online.'))return
  setBusy(true);try{const result=await client.post('/suite/fees/'+(modal==='charge'?'charges':'payments'),modal==='charge'?values:{...values,chargeId:modal?.id,idempotencyKey:key});setModal(null);setMessage(modal==='charge'?'Charge issued.':'Payment recorded. Receipt '+result.data.data.receipt);await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}
 }
 async function receipt(id:string){try{printSchoolDocument('receipt',await data('/fees/receipts/'+id))}catch(e){setError(errorMessage(e))}}
 async function remind(id:string){setBusy(true);try{const r=await client.post('/suite/fees/'+id+'/remind');setMessage(r.data.message)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <><PageHeader eyebrow="SCHOOL ACCOUNTS" title="Fees & receipts" description="Clear charges, concessions, payments, and outstanding balances.">{admin&&<><Link className="button secondary" to="/suite/fee-structures">Fee structures</Link><button className="button primary" onClick={()=>{setError('');setModal('charge')}}><Plus size={17}/>Issue charge</button></>}</PageHeader>
 <div className="info-box">This is a school payment ledger. Record payments only after funds are received. Receipts do not initiate an online payment. Charges and payments are retained as financial history.</div>
 {error&&!modal&&<ErrorBox message={error}/>} {message&&<div className="success-box" role="status">{message}</div>}
 <section className="panel"><div className="directory-toolbar"><h2>Charges & outstanding balances</h2><button className="button secondary" disabled={!fees.data?.length} onClick={()=>workbook('fee-balances',fees.data!)}><FileDown size={16}/>Excel export</button></div>
 {fees.isPending?<Loading/>:fees.isError?<ErrorBox message={errorMessage(fees.error)}/>:!fees.data.length?<Empty title="No charges issued" description={admin?'Create a fee structure and allocate students before issuing charges.':'Your school-issued fee charges will appear here.'}/>:<div className="table-scroll"><table><thead><tr><th>Student</th><th>Fee</th><th>Due</th><th>Gross</th><th>Concession</th><th>Paid</th><th>Balance</th>{admin&&<th>Actions</th>}</tr></thead><tbody>{fees.data.map(f=><tr key={f.id}><td>{f.student}</td><td>{f.description}</td><td>{String(f.dueDate).slice(0,10)}</td>{['gross','concession','paid','balance'].map(k=><td key={k}>{f.currency} {Number(f[k]).toFixed(2)}</td>)}{admin&&<td><div className="row-actions"><button className="button small primary" disabled={Number(f.balance)<=0} onClick={()=>{setError('');setKey(crypto.randomUUID());setModal(f)}}>Record payment</button><button className="icon-button" aria-label={'Remind '+f.student} disabled={busy||Number(f.balance)<=0} onClick={()=>remind(f.id)}><Send size={15}/></button></div></td>}</tr>)}</tbody></table></div>}</section>
 <section className="panel suite-section"><div className="panel-heading"><h2>Payment receipts</h2></div>{payments.isPending?<Loading/>:payments.isError?<ErrorBox message={errorMessage(payments.error)}/>:!payments.data.length?<Empty title="No payments recorded" description="Recorded payments and their printable receipts appear here."/>:<div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Student</th><th>Date</th><th>Amount</th><th>Method</th><th>Receipt</th></tr></thead><tbody>{payments.data.map(p=><tr key={p.id}><td>{p.receipt}</td><td>{p.student}</td><td>{String(p.paidOn).slice(0,10)}</td><td>{p.currency} {Number(p.amount).toFixed(2)}</td><td>{p.method}</td><td><button className="button secondary small" onClick={()=>receipt(p.id)}><Printer size={15}/>Print / Save PDF</button></td></tr>)}</tbody></table></div>}</section>
 {modal&&<Dialog title={modal==='charge'?'Issue student fee charge':'Record received payment'} onClose={()=>!busy&&setModal(null)}><form onSubmit={save}>{error&&<ErrorBox message={error}/>}<div className="form-stack">{modal==='charge'?<><label>Student<select name="studentId" required><option value="">Select student</option>{options.data?.students?.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label>Fee structure<select name="structureId" required><option value="">Select structure</option>{options.data?.['fee-structures']?.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label>Concession amount<input name="concession" type="number" min="0" step="0.01" required defaultValue="0"/></label></>:<><p>{modal.student} · {modal.description}<br/>Outstanding: {modal.currency} {Number(modal.balance).toFixed(2)}</p><label>Amount received<input name="amount" type="number" min="0.01" max={modal.balance} step="0.01" required/></label><label>Method<select name="method"><option>Cash</option><option>Bank transfer</option><option>UPI</option><option>Cheque</option></select></label><label>Reference<input name="reference" maxLength={150} placeholder="Required for bank, UPI, or cheque"/></label><label>Received on<input name="paidOn" type="date" defaultValue={today()} max={today()} required/></label></>}</div><div className="modal-footer"><button type="button" className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':modal==='charge'?'Issue charge':'Record payment'}</button></div></form></Dialog>}</>
}
export function AllocationPage(){
 const cache=useQueryClient(),[selected,setSelected]=useState<string[]>([]),[classId,setClass]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const options=useQuery<Options>({queryKey:['suite','options'],queryFn:()=>data('/options')}),allocated=useQuery<Row[]>({queryKey:['suite','allocations'],queryFn:()=>data('/allocations')})
 async function submit(){if(!window.confirm('Allocate or promote '+selected.length+' selected students to this class? Their previous class will be replaced.'))return;setBusy(true);setError('');try{await client.post('/suite/allocate',{studentIds:selected,classId});setMessage('Class allocation updated for '+selected.length+' students.');setSelected([]);await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <><PageHeader eyebrow="ACADEMIC SETUP" title="Class allocation & promotion" description="Assign existing or imported students to a class, or promote them into the next academic year."/>
 {error&&<ErrorBox message={error}/>} {message&&<div className="success-box">{message}</div>}
 <section className="panel"><div className="attendance-toolbar"><label>Destination class<select value={classId} onChange={e=>setClass(e.target.value)}><option value="">Select class and section</option>{options.data?.classes?.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><button className="button primary" disabled={!selected.length||!classId||busy} onClick={submit}>Allocate {selected.length} students</button></div>
 {options.isPending?<Loading/>:options.isError?<ErrorBox message={errorMessage(options.error)}/>:<div className="table-scroll"><table><thead><tr><th>Select</th><th>Student</th><th>Current allocated class</th></tr></thead><tbody>{options.data?.students.map(s=><tr key={s.id}><td><input className="table-checkbox" type="checkbox" aria-label={'Select '+s.label} checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/></td><td>{s.label}</td><td>{allocated.data?.find(a=>a.studentId===s.id)?.class||'Not allocated'}</td></tr>)}</tbody></table></div>}</section></>
}
export function RegisterPage(){
 const cache=useQueryClient(),[day,setDay]=useState(today()),[draft,setDraft]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const list=useQuery<Row[]>({queryKey:['suite','register',day],queryFn:()=>data('/student-attendance',{day})})
 async function save(){setBusy(true);setError('');try{await client.post('/suite/student-attendance',{day,entries:Object.entries(draft).map(([studentId,status])=>({studentId,status}))});setDraft({});setMessage('Attendance saved.');await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function notify(){setBusy(true);try{const r=await client.post('/suite/absence-notifications',{day});setMessage(r.data.message)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const admin=isAdmin(useAuthStore(s=>s.user?.roles[0]))
 return <><PageHeader eyebrow="DAILY ATTENDANCE" title="Student register" description="Administrators see the school; teachers see only students in their assigned classes."><button className="button primary" disabled={!Object.keys(draft).length||busy} onClick={save}><Save size={16}/>Save changes</button></PageHeader>
 {error&&<ErrorBox message={error}/>} {message&&<div className="success-box">{message}</div>}<section className="panel"><div className="attendance-toolbar"><label>Date<input type="date" value={day} max={today()} onChange={e=>{if(Object.keys(draft).length&&!window.confirm('Discard unsaved attendance?'))return;setDay(e.target.value);setDraft({})}}/></label>{admin&&<button className="button secondary" disabled={busy||!!Object.keys(draft).length} onClick={notify}><Send size={16}/>Issue absence notices</button>}<Link className="button secondary" to="/suite/reports">Monthly reports</Link></div>
 {list.isPending?<Loading/>:list.isError?<ErrorBox message={errorMessage(list.error)}/>:!list.data.length?<Empty title="No assigned students" description="Allocate students to classes and link the teacher account to its staff profile."/>:<div className="table-scroll"><table><thead><tr><th>Student</th><th>Admission number</th><th>Class</th><th>Status</th></tr></thead><tbody>{list.data.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.code}</td><td>{s.class}</td><td><select value={draft[s.id]||s.status||''} aria-label={'Attendance for '+s.name} onChange={e=>setDraft({...draft,[s.id]:e.target.value})}><option value="" disabled>Unmarked</option>{['Present','Absent','Late','Excused'].map(v=><option key={v}>{v}</option>)}</select></td></tr>)}</tbody></table></div>}</section></>
}
export function ReportsPage(){
 const role=useAuthStore(s=>s.user?.roles[0]),admin=isAdmin(role)
 const [type,setType]=useState('attendance'),[month,setMonth]=useState(today().slice(0,7)),[student,setStudent]=useState(''),[term,setTerm]=useState(''),[error,setError]=useState('')
 const options=useQuery<Options>({queryKey:['suite','options'],queryFn:()=>data('/options')})
 const rows=useQuery<Row[]>({queryKey:['suite','reports',type,month],queryFn:()=>data(type==='fees'?'/fees':'/reports/'+type,{month})})
 async function report(){try{const r=await data('/report-cards/'+student,{examName:term||undefined});if(!r.results.length)throw new Error('There are no published results for this selection.');printSchoolDocument('report',r)}catch(e){setError(errorMessage(e))}}
 const fields=Object.keys(rows.data?.[0]||{}).filter(k=>!['id','studentId','teacherId','version','createdAt'].includes(k))
 return <><PageHeader eyebrow="REPORTS & EXCEL TOOLS" title="School reports" description="Export the records you are authorized to view, or prepare a printable student report card."/>
 {error&&<ErrorBox message={error}/>}<section className="panel"><div className="attendance-toolbar"><label>Report<select value={type} onChange={e=>setType(e.target.value)}><option value="attendance">Monthly student attendance</option>{(admin||role==='Teacher')&&<option value="staff-attendance">Monthly staff attendance</option>}<option value="marks">Marks</option>{admin&&<option value="admissions">Admissions</option>}{role!=='Teacher'&&<option value="fees">Fee balances</option>}{admin&&<option value="audit">Attributed activity (latest 100)</option>}</select></label>{type.includes('attendance')&&<label>Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>}<button className="button secondary" disabled={!rows.data?.length} onClick={()=>workbook(type+'-'+month,rows.data!)}><FileDown size={16}/>Download Excel</button></div>
 {rows.isPending?<Loading/>:rows.isError?<ErrorBox message={errorMessage(rows.error)}/>:!rows.data.length?<Empty title="No records for this report" description="Saved school data will appear here when available."/>:<div className="table-scroll"><table><thead><tr>{fields.map(f=><th key={f}>{f.replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{rows.data.map((r,i)=><tr key={i}>{fields.map(f=><td key={f} className="truncate-cell">{String(r[f]??'—')}</td>)}</tr>)}</tbody></table></div>}</section>
 <section className="panel suite-section"><div className="panel-heading"><div><h2>Downloadable report card</h2><p>Only published exams with saved marks are included. Print or choose Save as PDF in your browser.</p></div></div><div className="attendance-toolbar"><label>Student<select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Select student</option>{options.data?.students.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label>Exam / term name (optional)<input value={term} onChange={e=>setTerm(e.target.value)} placeholder="All published exams"/></label><button className="button primary" disabled={!student} onClick={report}><Printer size={16}/>Open report card</button></div></section>
 {admin&&<ImportPanel/>}</>
}
function ImportPanel(){
 const cache=useQueryClient(),[kind,setKind]=useState('students'),[rows,setRows]=useState<Row[]>([]),[result,setResult]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const columns=kind==='students'?['rollNumber','firstName','lastName','email','phoneNumber','dateOfBirth','currentClass']:['employeeCode','firstName','lastName','email','phoneNumber','department']
 async function file(file:File){
  setError('');setResult(null);setRows([]);if(file.size>2*1024*1024){setError('Use a workbook smaller than 2 MB, with at most 500 rows.');return}setBusy(true)
  try{let parsed:Row[]=[]
   if(file.name.toLowerCase().endsWith('.csv')){const r=Papa.parse<Row>(await file.text(),{header:true,skipEmptyLines:true});if(r.errors.length)throw new Error('The CSV contains malformed rows.');parsed=r.data}
   else if(file.name.toLowerCase().endsWith('.xlsx')){const {readSheet}=await import('read-excel-file/universal');const sheet=await readSheet(await file.arrayBuffer());if(sheet.length>501)throw new Error('Maximum 500 data rows.');const headers=(sheet[0]||[]).map(v=>String(v??'').trim());if(new Set(headers).size!==headers.length)throw new Error('Column names must be unique.');parsed=sheet.slice(1).filter(row=>row.some(v=>v!==null)).map(row=>Object.fromEntries(headers.map((key,i)=>[key,row[i] instanceof Date?row[i].toISOString().slice(0,10):String(row[i]??'')])))}
   else throw new Error('Select an .xlsx or .csv file.')
   if(!parsed.length||parsed.length>500)throw new Error('Import between 1 and 500 data rows.')
   setRows(parsed);const r=await client.post('/suite/imports/'+kind,{rows:parsed,commit:false});setResult(r.data.data)
  }catch(e){setError(errorMessage(e))}finally{setBusy(false)}
 }
 async function commit(){if(!window.confirm('Import '+rows.length+' '+kind+'? All rows will be saved together, or none if a conflict occurs.'))return;setBusy(true);setError('');try{const r=await client.post('/suite/imports/'+kind,{rows,commit:true});setResult(r.data.data);await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <section className="panel suite-section"><div className="panel-heading"><div><h2>Import student or staff records</h2><p>Download the Excel template, enter values, upload, review validation, then confirm the import. Existing record numbers are never overwritten.</p></div></div><div className="attendance-toolbar"><label>Record type<select value={kind} onChange={e=>{setKind(e.target.value);setResult(null);setRows([])}}><option value="students">Students</option><option value="teachers">Teaching staff</option></select></label><button className="button secondary" onClick={()=>workbook(kind+'-import-template',[],columns.map(key=>({key,label:key})))}><FileDown size={16}/>Excel template</button><label className="upload-button"><Upload size={16}/>{busy?'Checking…':'Choose workbook'}<input type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{if(e.target.files?.[0])file(e.target.files[0]);e.target.value=''}}/></label></div>
 {error&&<ErrorBox message={error}/>} {result&&<div className="import-result">{result.errors?.length?<ErrorBox message={result.errors.slice(0,20).join(' ')}/>:<div className="success-box">{result.committed?result.count+' records imported.':result.count+' rows passed field validation. Existing-record conflicts are checked during commit.'}</div>}{result.valid&&!result.committed&&<button className="button primary" disabled={busy} onClick={commit}>Confirm import of {rows.length} records</button>}</div>}</section>
}
