-- Additive billing migration. Applied transactionally on every start; safe to repeat.
-- Money is stored in minor units of its currency (paise for INR). Nothing here deletes school data.
CREATE SCHEMA IF NOT EXISTS billing;
CREATE TABLE IF NOT EXISTS billing.plans (
 id uuid PRIMARY KEY, name varchar(100) NOT NULL, description text NOT NULL DEFAULT '',
 status text NOT NULL DEFAULT 'Active' CHECK(status IN ('Active','Disabled')),
 billing_period text NOT NULL DEFAULT 'yearly' CHECK(billing_period IN ('monthly','quarterly','yearly')),
 base_price bigint NOT NULL CHECK(base_price >= 0), currency varchar(3) NOT NULL DEFAULT 'INR',
 trial_days int NOT NULL DEFAULT 0 CHECK(trial_days BETWEEN 0 AND 365),
 features text[] NOT NULL DEFAULT '{}', display_order int NOT NULL DEFAULT 0, highlighted boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS plans_name ON billing.plans(lower(name));
-- code IS NULL means an automatic promotion that needs no coupon.
CREATE TABLE IF NOT EXISTS billing.offers (
 id uuid PRIMARY KEY, name varchar(100) NOT NULL, code varchar(40), description text NOT NULL DEFAULT '',
 discount_type text NOT NULL CHECK(discount_type IN ('percent','fixed')),
 discount_value bigint NOT NULL CHECK(discount_value > 0), currency varchar(3) NOT NULL DEFAULT 'INR',
 starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL,
 status text NOT NULL DEFAULT 'Draft' CHECK(status IN ('Draft','Active','Disabled')),
 plan_ids uuid[] NOT NULL DEFAULT '{}', school_ids uuid[] NOT NULL DEFAULT '{}',
 new_customers_only boolean NOT NULL DEFAULT false, max_uses int CHECK(max_uses > 0), used int NOT NULL DEFAULT 0,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK(ends_at > starts_at), CHECK(discount_type <> 'percent' OR discount_value <= 100));
CREATE UNIQUE INDEX IF NOT EXISTS offers_code ON billing.offers(upper(code)) WHERE code IS NOT NULL;
CREATE TABLE IF NOT EXISTS billing.banners (
 id uuid PRIMARY KEY, title varchar(120) NOT NULL, message varchar(500) NOT NULL DEFAULT '',
 cta_label varchar(60) NOT NULL DEFAULT '', cta_url varchar(300) NOT NULL DEFAULT '',
 placement text NOT NULL CHECK(placement IN ('login','pricing','admin-dashboard','subscription')),
 enabled boolean NOT NULL DEFAULT false, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), CHECK(ends_at > starts_at));
-- Grace Period and Expired are derived from ends_at and settings.grace_days; they are never stored.
CREATE TABLE IF NOT EXISTS billing.subscriptions (
 school_id uuid PRIMARY KEY REFERENCES school_db.schools(id), plan_id uuid REFERENCES billing.plans(id),
 status text NOT NULL CHECK(status IN ('Trial','Active','Complimentary','Cancelled')), previous_status text,
 starts_at timestamptz NOT NULL DEFAULT now(), ends_at timestamptz, billing_period text,
 base_price bigint NOT NULL DEFAULT 0, discount bigint NOT NULL DEFAULT 0, final_amount bigint NOT NULL DEFAULT 0,
 currency varchar(3) NOT NULL DEFAULT 'INR',
 payment_state text NOT NULL DEFAULT 'NotRequired' CHECK(payment_state IN ('NotRequired','Paid')),
 note text NOT NULL DEFAULT '', modified_by uuid,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- A school-specific price takes precedence over the plan's base price.
CREATE TABLE IF NOT EXISTS billing.school_prices (
 school_id uuid NOT NULL REFERENCES school_db.schools(id), plan_id uuid NOT NULL REFERENCES billing.plans(id),
 price bigint NOT NULL CHECK(price >= 0), note text NOT NULL DEFAULT '', modified_by uuid,
 updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(school_id, plan_id));
-- Provider references only. No card, CVV or UPI data is ever stored.
CREATE TABLE IF NOT EXISTS billing.payments (
 id uuid PRIMARY KEY, school_id uuid NOT NULL REFERENCES school_db.schools(id), plan_id uuid NOT NULL REFERENCES billing.plans(id),
 offer_id uuid REFERENCES billing.offers(id), provider text NOT NULL DEFAULT 'razorpay',
 provider_order_id varchar(64) NOT NULL UNIQUE, provider_payment_id varchar(64),
 base_amount bigint NOT NULL, discount bigint NOT NULL, amount bigint NOT NULL CHECK(amount > 0), currency varchar(3) NOT NULL,
 billing_period text NOT NULL, status text NOT NULL DEFAULT 'Created' CHECK(status IN ('Created','Paid','Failed','Cancelled')),
 failure_reason text, receipt_no bigint GENERATED BY DEFAULT AS IDENTITY, created_by uuid,
 created_at timestamptz NOT NULL DEFAULT now(), verified_at timestamptz);
CREATE INDEX IF NOT EXISTS payments_school ON billing.payments(school_id, created_at DESC);
CREATE TABLE IF NOT EXISTS billing.webhook_events (
 event_id varchar(100) PRIMARY KEY, event text NOT NULL, received_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS billing.settings (
 id boolean PRIMARY KEY DEFAULT true CHECK(id), grace_days int NOT NULL DEFAULT 7 CHECK(grace_days BETWEEN 0 AND 90));
INSERT INTO billing.settings DEFAULT VALUES ON CONFLICT DO NOTHING;

-- One-time grant of the new permissions to existing installations. Later starts never restore a
-- permission that the platform administrator has removed.
DO $$
DECLARE school_keys text[] := ARRAY['subscription.view','subscription.purchase'];
 platform_keys text[] := ARRAY['billing.view','billing.plans.manage','billing.offers.manage','billing.subscriptions.manage','billing.payments.view','billing.settings.manage'];
BEGIN
 IF NOT EXISTS(SELECT 1 FROM auth_db.schema_migrations WHERE id='20261002_01_billing') THEN
  UPDATE auth_db.permissions SET delegatable=false WHERE key=ANY(platform_keys);
  UPDATE auth_db.role_templates SET maximum=ARRAY(SELECT DISTINCT unnest(maximum||school_keys)), defaults=ARRAY(SELECT DISTINCT unnest(defaults||school_keys)) WHERE name='Administrator';
  UPDATE auth_db.role_templates SET maximum=ARRAY(SELECT DISTINCT unnest(maximum||platform_keys)), defaults=ARRAY(SELECT DISTINCT unnest(defaults||platform_keys)) WHERE name='SuperAdmin';
  UPDATE auth_db.school_access SET allowed=ARRAY(SELECT DISTINCT unnest(allowed||school_keys));
  INSERT INTO auth_db.role_permissions(id,role_id,permission_key)
  SELECT gen_random_uuid(),r.id,k FROM auth_db.roles r JOIN auth_db.role_templates t ON t.id=r.template_id
  CROSS JOIN unnest(CASE t.name WHEN 'Administrator' THEN school_keys ELSE platform_keys END) k
  WHERE t.name IN ('Administrator','SuperAdmin') AND r.name=t.name
  AND NOT EXISTS(SELECT 1 FROM auth_db.role_permissions rp WHERE rp.role_id=r.id AND rp.permission_key=k);
  -- Access tokens carry permissions, so the affected accounts sign in again to receive the new ones.
  UPDATE auth_db.users SET token_version=token_version+1 WHERE role_id IN
  (SELECT r.id FROM auth_db.roles r JOIN auth_db.role_templates t ON t.id=r.template_id WHERE t.name IN ('Administrator','SuperAdmin') AND r.name=t.name);
  INSERT INTO auth_db.schema_migrations(id) VALUES ('20261002_01_billing');
 END IF;
END $$;
