import { GuardianMismatchOverview, GuardianStudentPicker } from '../components/GuardianReview'
import { FormEvent, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import client, { errorMessage } from '../api/client'
import { useAuthStore } from '../store/auth'
import { Dialog, ErrorBox, Loading, PageHeader } from '../components/UI'

type Permission = {key:string,module:string,enabled:boolean,delegatable:boolean}
type Template = {id:string,name:string,description:string,dataScope:string,enabled:boolean,assignable:boolean,maximum:string[],defaults:string[]}
type Role = {id:string,name:string,description:string,templateId:string,dataScope:string,enabled:boolean,assignable:boolean,permissions:string[],effectivePermissions:string[],maximum:string[],users:number,canAssign:boolean}
type Configuration = {roles:Role[],templates:Template[],permissions:Permission[],boundary:{allowed:string[],signupCode:string}|null}
type Account = {id:string,firstName:string,lastName:string,email:string,phoneNumber:string,roleId:string,role:string,isActive:boolean,createdAt:string,lastLoginAt?:string}
type Request = {id:string,firstName:string,lastName:string,email:string,phone:string,requestedRole:string,status:string,createdAt:string,reason?:string}
const sections=[['','Overview'],['users','Users'],['roles','Roles'],['permissions','Permissions'],['role-permissions','Role permissions'],['signup-requests','Signup requests'],['access-history','Access history']]

export default function AccessControlPage(){
 const user=useAuthStore(s=>s.user),platform=user?.dataScope==='platform',location=useLocation(),cache=useQueryClient()
 const [creating,setCreating]=useState(false)
 const [school,setSchool]=useState(''),[section,setSection]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[roleFilter,setRoleFilter]=useState(''),[page,setPage]=useState(1)
 const [roleEdit,setRoleEdit]=useState<Role|null>(),[templateEdit,setTemplateEdit]=useState<Template|null>(),[account,setAccount]=useState<Account>(),[review,setReview]=useState<Request>(),[details,setDetails]=useState<string>()
 const tab=platform?section:location.pathname.split('/')[2]||''
 const params=platform?{targetSchool:school}:{}
 const ready=!platform||!!school
 const schools=useQuery<{id:string,name:string}[]>({queryKey:['iam-schools'],enabled:platform,queryFn:async()=>(await client.get('/platform/schools')).data.data})
 const config=useQuery<Configuration>({queryKey:['iam-config',school],enabled:ready,queryFn:async()=>(await client.get('/control/configuration',{params})).data.data})
 const users=useQuery<{data:Account[],totalCount:number}>({queryKey:['iam-users',school,search,status,roleFilter,page],enabled:ready&&tab==='users',queryFn:async()=>(await client.get('/control/users',{params:{...params,search,status,roleId:roleFilter||undefined,page}})).data.data})
 const requests=useQuery<Request[]>({queryKey:['iam-requests',school],enabled:ready&&tab==='signup-requests',queryFn:async()=>(await client.get('/control/signup-requests',{params})).data.data})
 const history=useQuery<Record<string,unknown>[]>({queryKey:['iam-history',school,page],enabled:ready&&tab==='access-history',queryFn:async()=>(await client.get('/control/access-history',{params:{...params,page}})).data.data})
 const profiles=useQuery<{students:{id:string,label:string}[],teachers:{id:string,label:string}[]}>({queryKey:['iam-profiles',school],enabled:ready&&!!review,queryFn:async()=>(await client.get('/control/profiles',{params})).data.data})
 async function action(fn:()=>Promise<unknown>){setBusy(true);setError('');setMessage('');try{await fn();setMessage('Saved. Affected users must sign in again.');setRoleEdit(undefined);setTemplateEdit(undefined);setAccount(undefined);setReview(undefined);setCreating(false);await cache.invalidateQueries({queryKey:['iam-config']});await cache.invalidateQueries({queryKey:['iam-users']});await cache.invalidateQueries({queryKey:['iam-requests']});await cache.invalidateQueries({queryKey:['iam-history']})}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const can=(permission:string)=>platform||user?.permissions.includes(permission)
 const tabs=sections.filter(([key])=>can(key==='users'?'users.view':key==='signup-requests'?'signup.review':key==='access-history'?'access-history.view':key==='permissions'?'permissions.view':'roles.view'))
 return <><PageHeader eyebrow={platform?'PLATFORM GOVERNANCE':'SCHOOL ADMINISTRATION'} title="Access control" description="Review accounts, assign roles, and configure the permissions your school can use."/>
 {platform&&<label>School workspace<select value={school} onChange={e=>{setSchool(e.target.value);setPage(1)}}><option value="">Select a school</option><option value="00000000-0000-0000-0000-00000000e005">Platform roles and global configuration</option>{schools.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
 <nav className="module-tabs" aria-label="Access control">{tabs.map(([key,label])=>platform?<button key={key} className={'button '+(tab===key?'primary':'secondary')} onClick={()=>{setSection(key);setPage(1)}}>{label}</button>:<Link key={key} className={tab===key?'selected':''} to={'/control'+(key?'/'+key:'')} onClick={()=>setPage(1)}>{label}</Link>)}</nav>
 {error&&<ErrorBox message={error}/>} {message&&<div role="status" className="success-box">{message}</div>}
 {ready&&config.isPending?<Loading/>:config.isError?<ErrorBox message={errorMessage(config.error)}/>:config.data&&<>
 {tab===''&&<section className="panel" style={{padding:24}}><h2>School access</h2><p>{config.data.roles.length} roles · {config.data.roles.reduce((n,r)=>n+r.users,0)} accounts</p><p>Role permissions are limited by the platform template, school boundary, and permission availability.</p>{config.data.boundary&&<p>School signup code: <strong>{config.data.boundary.signupCode}</strong></p>}<p>Parent and student relationships are verified separately. Role changes preserve existing profile links.</p></section>}
 {tab===''&&can('account-links.view')&&can('users.view')&&<GuardianMismatchOverview key={school} targetSchool={platform?school:undefined}/>}
 {tab==='users'&&<section className="panel" style={{padding:20}}>{can('users.create')&&<button className="button primary" onClick={()=>setCreating(true)}>Create account</button>}<div className="toolbar-actions"><label>Search<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><label>Role<select value={roleFilter} onChange={e=>{setRoleFilter(e.target.value);setPage(1)}}><option value="">All roles</option>{config.data.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label></div>
 {users.isError?<ErrorBox message={errorMessage(users.error)}/>:<div className="table-scroll"><table><thead><tr><th>Name</th><th>Contact</th><th>Role</th><th>Status</th><th>Created / last login</th><th>Actions</th></tr></thead><tbody>{users.data?.data.map(u=><tr key={u.id}><td>{u.firstName} {u.lastName}</td><td>{u.email}<br/>{u.phoneNumber}</td><td>{u.role}</td><td>{u.isActive?'Active':'Disabled'}</td><td>{new Date(u.createdAt).toLocaleDateString()}<br/>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'Never signed in'}</td><td><div className="row-actions">{can('roles.assign')&&<button className="button secondary" onClick={()=>setAccount(u)}>Manage access</button>}<button className="button secondary" onClick={()=>void action(async()=>{const r=await client.get('/control/users/'+u.id+'/permissions',{params});setDetails(r.data.data.permissions.join('\n')||'No effective permissions')})}>Effective permissions</button>{can('users.update')&&<button className="button secondary" onClick={()=>void action(async()=>{const r=await client.post('/control/users/'+u.id+'/recovery',{}, {params});setDetails('One-time recovery code (15 minutes):\n'+r.data.data.code+'\nShare privately with the verified account holder.')})}>Recovery</button>}</div></td></tr>)}</tbody></table></div>}
 <div className="toolbar-actions"><button className="button secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} · {users.data?.totalCount??0} accounts</span><button className="button secondary" disabled={page*20>=(users.data?.totalCount??0)} onClick={()=>setPage(page+1)}>Next</button></div></section>}
 {(tab==='roles'||tab==='role-permissions')&&<><div className="toolbar-actions">{can('roles.manage')&&<button className="button primary" onClick={()=>setRoleEdit(null)}>Create role</button>}{platform&&<button className="button secondary" onClick={()=>setTemplateEdit(null)}>Create role template</button>}</div><div className="table-scroll panel"><table><thead><tr><th>Role</th><th>Data scope</th><th>Users</th><th>Permissions</th><th>Status</th><th>Actions</th></tr></thead><tbody>{config.data.roles.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.dataScope}</td><td>{r.users}</td><td>{r.effectivePermissions?.length??0}</td><td>{r.enabled?'Enabled':'Disabled'}</td><td><button className="button secondary" onClick={()=>setRoleEdit(r)}>View / edit</button></td></tr>)}</tbody></table></div>{platform&&<section className="panel" style={{padding:20}}><h2>Platform role templates</h2>{config.data.templates.filter(t=>t.name!=='SuperAdmin').map(t=><button key={t.id} className="button secondary" onClick={()=>setTemplateEdit(t)}>{t.name} · {t.maximum.length} maximum permissions</button>)}</section>}
 {tab==='role-permissions'&&<div className="table-scroll panel"><table><thead><tr><th>Permission</th>{config.data.roles.map(r=><th key={r.id}>{r.name}</th>)}</tr></thead><tbody>{config.data.permissions.map(p=><tr key={p.key}><td>{p.key}</td>{config.data.roles.map(r=><td key={r.id}>{r.enabled&&r.maximum.includes(p.key)&&r.permissions.includes(p.key)?'✓':'—'}</td>)}</tr>)}</tbody></table></div>}</>}
 {tab==='permissions'&&<section className="panel" style={{padding:20}}><h2>Permission catalogue</h2>{platform&&config.data.boundary&&<button className="button secondary" onClick={()=>setDetails('School boundary: '+config.data!.boundary!.allowed.join(', '))}>View school boundary</button>}<div className="table-scroll"><table><thead><tr><th>Module</th><th>Permission</th><th>Availability</th><th>School delegation</th>{platform&&<th>School boundary</th>}</tr></thead><tbody>{config.data.permissions.map(p=><tr key={p.key}><td>{p.module}</td><td>{p.key}</td><td>{platform?<input aria-label={'Enable '+p.key} type="checkbox" checked={p.enabled} disabled={busy} onChange={e=>void action(()=>client.put('/control/permissions/'+p.key,{...p,enabled:e.target.checked}))}/>:p.enabled?'Enabled':'Disabled'}</td><td>{platform?<input aria-label={'Delegate '+p.key} type="checkbox" checked={p.delegatable} disabled={busy} onChange={e=>void action(()=>client.put('/control/permissions/'+p.key,{...p,delegatable:e.target.checked}))}/>:p.delegatable?'Delegatable':'Controlled by Platform Administrator'}</td>{platform&&<td>{config.data!.boundary&&<input aria-label={'Allow school '+p.key} type="checkbox" checked={config.data!.boundary.allowed.includes(p.key)} disabled={busy} onChange={e=>void action(()=>client.put('/control/boundary',{allowed:e.target.checked?[...config.data!.boundary!.allowed,p.key]:config.data!.boundary!.allowed.filter(x=>x!==p.key)},{params}))}/>}</td>}</tr>)}</tbody></table></div></section>}
 {tab==='signup-requests'&&<div className="panel table-scroll">{requests.isError?<ErrorBox message={errorMessage(requests.error)}/>:<table><thead><tr><th>Applicant</th><th>Contact</th><th>Requested category</th><th>Submitted</th><th>Status</th><th>Review</th></tr></thead><tbody>{requests.data?.map(r=><tr key={r.id}><td>{r.firstName} {r.lastName}</td><td>{r.email}<br/>{r.phone}</td><td>{r.requestedRole}</td><td>{new Date(r.createdAt).toLocaleString()}</td><td>{r.status}</td><td>{r.status==='Pending'?<button className="button primary" onClick={()=>setReview(r)}>Review request</button>:r.reason}</td></tr>)}</tbody></table>}</div>}
 {tab==='access-history'&&<section className="panel" style={{padding:20}}>{history.isError?<ErrorBox message={errorMessage(history.error)}/>:history.data?.map(r=><details key={String(r.id)}><summary>{new Date(String(r.created_at)).toLocaleString()} · {String(r.action)} · {String(r.actor_role)}</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(r,null,2)}</pre></details>)}<button className="button secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span> Page {page} </span><button className="button secondary" disabled={(history.data?.length??0)<50} onClick={()=>setPage(page+1)}>Next</button></section>}
 {roleEdit!==undefined&&<RoleEditor config={config.data} role={roleEdit} platform={!!platform} busy={busy} close={()=>setRoleEdit(undefined)} save={body=>void action(()=>roleEdit?client.put('/control/roles/'+roleEdit.id,body,{params}):client.post('/control/roles',body,{params}))}/>}
 {templateEdit!==undefined&&<TemplateEditor config={config.data} template={templateEdit} busy={busy} close={()=>setTemplateEdit(undefined)} save={body=>void action(()=>client.put('/control/templates/'+body.id,body))}/>}
 {account&&<Dialog title={'Manage '+account.firstName+' '+account.lastName} onClose={()=>setAccount(undefined)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(()=>client.put('/control/users/'+account.id,{roleId:f.get('roleId'),isActive:f.get('active')==='on',firstName:f.get('firstName'),lastName:f.get('lastName'),email:f.get('email'),phoneNumber:f.get('phoneNumber')},{params}))}}><label>First name<input name="firstName" required maxLength={100} defaultValue={account.firstName}/></label><label>Last name<input name="lastName" required maxLength={100} defaultValue={account.lastName}/></label><label>Email<input name="email" type="email" required defaultValue={account.email}/></label><label>Phone<input name="phoneNumber" maxLength={20} defaultValue={account.phoneNumber}/></label><label>Assigned role<select name="roleId" defaultValue={account.roleId} required>{config.data.roles.filter(r=>r.canAssign||r.id===account.roleId).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label><input type="checkbox" name="active" defaultChecked={account.isActive}/> Account active</label><p>Saving ends all current sessions. Existing profile links remain intact.</p><button className="button primary" disabled={busy}>Save access</button></form></Dialog>}
 {creating&&<Dialog title="Create account" onClose={()=>setCreating(false)}><form onSubmit={e=>{e.preventDefault();void action(()=>client.post("/control/users",Object.fromEntries(new FormData(e.currentTarget)),{params}))}}>{["firstName","lastName","username","email","password"].map(name=><label key={name}>{({firstName:"First name",lastName:"Last name",username:"Username",email:"Email",password:"Password"})[name]}<input name={name} required type={name==="password"?"password":name==="email"?"email":"text"} minLength={name==="password"?16:1} maxLength={name==="password"?72:name==="email"?255:100}/></label>)}<label>Approved role<select name="roleId" required><option value="">Select a role</option>{config.data.roles.filter(r=>r.canAssign).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="button primary" disabled={busy}>Create account</button></form></Dialog>}
 {review&&<ReviewDialog targetSchool={platform?school:undefined} request={review} roles={config.data.roles.filter(r=>r.canAssign)} profiles={profiles.data} busy={busy} close={()=>setReview(undefined)} save={body=>void action(()=>client.post('/control/signup-requests/'+review.id+'/review',body,{params}))}/>}
 </>}{details&&<Dialog title="Account access details" onClose={()=>setDetails(undefined)}><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{details}</pre></Dialog>}</>
}

function PermissionPicker({permissions,selected,allowed,onChange}:{permissions:Permission[],selected:string[],allowed:string[],onChange:(keys:string[])=>void}){
 return <>{[...new Set(permissions.map(p=>p.module))].map(module=><fieldset key={module}><legend>{module}</legend>{permissions.filter(p=>p.module===module).map(p=><label key={p.key} style={{display:'block',margin:'8px 0'}}><input type="checkbox" checked={selected.includes(p.key)} disabled={!allowed.includes(p.key)} onChange={e=>onChange(e.target.checked?[...selected,p.key]:selected.filter(k=>k!==p.key))}/> {p.key}{!allowed.includes(p.key)&&<small> — Controlled by Platform Administrator</small>}</label>)}</fieldset>)}</>
}
function RoleEditor({config,role,platform,busy,close,save}:{config:Configuration,role:Role|null,platform:boolean,busy:boolean,close:()=>void,save:(body:unknown)=>void}){
 const [template,setTemplate]=useState(role?.templateId||''),[selected,setSelected]=useState(role?.permissions||[])
 const t=config.templates.find(t=>t.id===template)
 const allowed=role?.maximum||t?.maximum.filter(k=>config.permissions.some(p=>p.key===k&&p.enabled&&(platform||p.delegatable))&&(!config.boundary||config.boundary.allowed.includes(k)))||[]
 return <Dialog title={role?'Edit role':'Create role'} onClose={close}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({name:f.get('name'),description:f.get('description'),templateId:template,enabled:f.get('enabled')==='on',assignable:f.get('assignable')==='on',permissions:selected.filter(k=>allowed.includes(k))})}}><label>Role name<input name="name" defaultValue={role?.name} required maxLength={100}/></label><label>Description<textarea name="description" defaultValue={role?.description} maxLength={1000}/></label><label>Platform template<select required value={template} disabled={!!role} onChange={e=>{setTemplate(e.target.value);setSelected([])}}><option value="">Select a template</option>{config.templates.map(t=><option key={t.id} value={t.id}>{t.name} ({t.dataScope})</option>)}</select></label><label><input type="checkbox" name="enabled" defaultChecked={role?.enabled??true}/> Enabled</label>{platform&&<label><input type="checkbox" name="assignable" defaultChecked={role?.assignable??true}/> School administrators may assign this role</label>}<PermissionPicker permissions={config.permissions} selected={selected} allowed={allowed} onChange={setSelected}/><button className="button primary" disabled={busy||!template||(!platform&&role?.assignable===false)}>Save role</button></form></Dialog>
}
function TemplateEditor({config,template,busy,close,save}:{config:Configuration,template:Template|null,busy:boolean,close:()=>void,save:(body:Template)=>void}){
 const [maximum,setMaximum]=useState(template?.maximum||[]),[defaults,setDefaults]=useState(template?.defaults||[])
 return <Dialog title="Platform role template" onClose={close}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({id:template?.id||crypto.randomUUID(),name:String(f.get('name')),description:String(f.get('description')),dataScope:template?.dataScope||String(f.get('scope')),enabled:f.get('enabled')==='on',assignable:f.get('assignable')==='on',maximum,defaults:defaults.filter(k=>maximum.includes(k))})}}><label>Name<input name="name" required defaultValue={template?.name}/></label><label>Description<textarea name="description" defaultValue={template?.description}/></label><label>Data scope<select name="scope" defaultValue={template?.dataScope||'school'} disabled={!!template}>{['school','teacher','parent','student','platform'].map(s=><option key={s}>{s}</option>)}</select></label><label><input type="checkbox" name="enabled" defaultChecked={template?.enabled??true}/> Enabled</label><label><input type="checkbox" name="assignable" defaultChecked={template?.assignable??true}/> Delegatable role template</label><h3>Maximum permissions</h3><PermissionPicker permissions={config.permissions} selected={maximum} allowed={config.permissions.map(p=>p.key)} onChange={setMaximum}/><h3>Default permissions</h3><PermissionPicker permissions={config.permissions} selected={defaults} allowed={maximum} onChange={setDefaults}/><button className="button primary" disabled={busy}>Save template</button></form></Dialog>
}
function ReviewDialog({request,roles,profiles,busy,close,save,targetSchool}:{targetSchool?:string,request:Request,roles:Role[],profiles?:{students:{id:string,label:string}[],teachers:{id:string,label:string}[]},busy:boolean,close:()=>void,save:(body:unknown)=>void}){
 const [roleId,setRoleId]=useState('');const role=roles.find(r=>r.id===roleId)
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const approve=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='approve';save({approve,roleId:roleId||null,reason:f.get('reason'),studentId:f.get('studentId')||null,teacherId:f.get('teacherId')||null})}
 return <Dialog title="Review signup request" onClose={close}><p>{request.firstName} {request.lastName} · {request.email}<br/>Requested: {request.requestedRole}</p><form onSubmit={submit}><label>Approved role<select value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">Select the actual role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{role&&<p>Resulting permissions: {role.effectivePermissions?.join(', ')||'None'}</p>}{role?.dataScope==='parent'&&<GuardianStudentPicker key={request.id} signupRequestId={request.id} targetSchool={targetSchool}/>} {role?.dataScope==='student'&&<label>Verified student record<select name="studentId"><option value="">Select a student</option>{profiles?.students.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>}{role?.dataScope==='teacher'&&<label>Verified teacher profile<select name="teacherId"><option value="">Select a teacher</option>{profiles?.teachers.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>}<label>Review reason<textarea name="reason" maxLength={1000}/></label><div className="toolbar-actions"><button className="button primary" value="approve" disabled={busy||!roleId}>Approve</button><button className="button secondary" value="reject" disabled={busy}>Reject</button></div></form></Dialog>
}
