import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { ArrowUpRight, Plus, GraduationCap, BookOpen, Users, Layers, CalendarCheck, Megaphone, CheckCircle2, ArrowRight } from 'lucide-react'
import client, { errorMessage } from '../api/client'
import { useAuthStore } from '../store/auth'
import { Empty, ErrorBox, Loading, PageHeader, today } from '../components/UI'
import { FeeSummary, UpcomingExams } from './portals/widgets'
import { PromoBanner } from './billing/shared'
type Overview={stats:{students:number,teachers:number,parents:number,classes:number,present:number,marked:number},classes:{name:string,count:number}[]}
type Notice={id:string,title:string,body:string,priority:string,createdAt:string}
export default function DashboardPage(){
 const user=useAuthStore(s=>s.user)
 const overview=useQuery<Overview>({queryKey:['overview',today()],queryFn:async()=>(await client.get('/operations/overview',{params:{day:today()}})).data.data})
 const notices=useQuery<Notice[]>({queryKey:['announcements'],queryFn:async()=>(await client.get('/operations/announcements')).data.data})
 const school=useQuery({queryKey:['school',user?.schoolId],queryFn:async()=>(await client.get('/schools/'+user?.schoolId)).data.data})
 const s=overview.data?.stats
 const hour=new Date().getHours(), greeting=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening'
 return <><PageHeader eyebrow="A LITTLE CLARITY FOR YOUR DAY" title={greeting+', '+(user?.firstName || 'Administrator')+'.'} description="Administrator portal · here is what is happening across your school today."><Link className="button primary" to="/students"><Plus size={17}/>Add a student</Link></PageHeader>
 <PromoBanner placement="admin-dashboard"/>
 <section className="welcome-banner"><div><span className="banner-label"><span/>YOUR SCHOOL, CONNECTED</span><h2>A great school day<br/>starts with a clear view.</h2><p>People, progress, and everyday moments.<br/>All together at {school.data?.name || 'your school'}.</p><Link to="/attendance">Open today's register <ArrowRight size={17}/></Link></div><div className="banner-art" aria-hidden="true"><div className="banner-circle"/><div className="mini-card"><span className="mini-icon"><CalendarCheck size={25}/></span><span>Today's focus</span><strong>Every student counts.</strong><div className="mini-line"/><div className="mini-check"><CheckCircle2 size={17}/>Take attendance. Stay connected.</div></div><div className="floating-book"><BookOpen size={30}/></div></div></section>
 {overview.isError?<ErrorBox message={errorMessage(overview.error)}/>:overview.isPending?<Loading/>:<><div className="stats-grid">{[
 {label:'Total students',value:s?.students,icon:GraduationCap,tone:'teal',note:'Your student community',path:'/students'},
 {label:'Teaching staff',value:s?.teachers,icon:BookOpen,tone:'blue',note:'People shaping futures',path:'/teachers'},
 {label:'Parents & guardians',value:s?.parents,icon:Users,tone:'peach',note:'Your family network',path:'/parents'},
 {label:'Active class groups',value:s?.classes,icon:Layers,tone:'purple',note:'From student enrollments',path:'/suite/classes'}
 ].map(({label,value,icon:Icon,tone,note,path})=><Link className="stat-card" to={path} key={label}><div className="stat-top"><span className={'stat-icon '+tone}><Icon size={20}/></span><ArrowUpRight size={17}/></div><strong>{Number(value||0).toLocaleString()}</strong><h3>{label}</h3><p>{note}</p></Link>)}</div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>Attendance at a glance</h2><p>Today's register · {new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long'})}</p></div><span className="tag">Today</span></div><div className="attendance-summary"><div className="attendance-ring" style={{'--progress':((Number(s?.marked)?Number(s?.present)/Number(s?.marked):0)*100)+'%'} as React.CSSProperties}><div><strong>{s?.marked?Math.round(Number(s.present)/Number(s.marked)*100)+'%':'—'}</strong><span>present</span></div></div><div className="attendance-numbers"><p><span className="dot teal-dot"/>Present & late<strong>{s?.present||0}</strong></p><p><span className="dot peach-dot"/>Absent & excused<strong>{Number(s?.marked||0)-Number(s?.present||0)}</strong></p><p><span className="dot gray-dot"/>Unmarked students<strong>{Math.max(0,Number(s?.students||0)-Number(s?.marked||0))}</strong></p></div></div><Link className="panel-link" to="/attendance">Continue taking attendance <ArrowRight size={16}/></Link></section>
 <section className="panel"><div className="panel-heading"><div><h2>Class distribution</h2><p>Enrollment across your school</p></div><Layers size={19}/></div>{overview.data?.classes.length?<div className="class-bars">{overview.data.classes.slice(0,6).map(c=><div key={c.name}><span>{c.name}</span><div><i style={{width:(Number(c.count)/Math.max(...overview.data.classes.map(c=>Number(c.count)))*100)+'%'}}/></div><strong>{c.count}</strong></div>)}</div>:<Empty title="Your classes will appear here" description="Add students with a class group to see enrollment."/>}</section></div></>}
 <div className="dashboard-grid"><FeeSummary title="Fee collection" description="Charges, payments and outstanding balances" link="/suite/fees"/><UpcomingExams link="/suite/exams"/></div>
 <div className="dashboard-grid lower-grid"><section className="panel"><div className="panel-heading"><div><h2>School noticeboard</h2><p>Keep your administration team in the loop</p></div><Link className="text-link" to="/announcements">View all <ArrowUpRight size={15}/></Link></div>{notices.isError?<ErrorBox message={errorMessage(notices.error)}/>:notices.isPending?<Loading/>:notices.data?.length?<div className="notice-list">{notices.data.slice(0,3).map(n=><Link to="/announcements" key={n.id}><span className={'notice-icon '+(n.priority==='Important'?'peach':'teal')}><Megaphone size={19}/></span><div><h3>{n.title}</h3><p>{n.body.slice(0,95)}{n.body.length>95?'…':''}</p><small>{new Date(n.createdAt).toLocaleDateString()}</small></div></Link>)}</div>:<Empty title="A fresh noticeboard" description="Publish your first school update to bring the team together."/>}</section><section className="panel quick-start"><div className="panel-heading"><div><h2>Make yourself at home</h2><p>A few good places to start</p></div></div>{[['01','Set up your school','Name, leadership, accounts and roles','/settings'],['02','Enrol students','Admissions, class allocation and profiles','/suite/admissions'],['03','Start the daily rhythm','Take attendance and share updates','/attendance'],['04','Collect fees','Issue charges and record received payments','/suite/fees']].map(([n,title,desc,path])=><Link key={n} to={path}><span>{n}</span><div><h3>{title}</h3><p>{desc}</p></div><ArrowUpRight size={17}/></Link>)}</section></div></>
}
