import { FormEvent, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Search, Download, Pencil, Archive, Users } from 'lucide-react'
import client, { errorMessage } from '../api/client'
import { useAuthStore } from '../store/auth'
import { Dialog, Empty, ErrorBox, Loading, PageHeader, Pagination, exportCsv, today } from '../components/UI'
import { isAdministrator, roleOf } from '../roles'
type Kind='students'|'teachers'|'parents'
export type Person={id:string,firstName:string,lastName:string,email:string,phoneNumber:string,currentClass?:string,rollNumber?:string,employeeCode?:string,department?:string,status?:string,dateOfBirth?:string}
const labels={students:{title:'Students',singular:'student',description:'A home for every student record. Keep your school community connected.'},teachers:{title:'Teachers',singular:'teacher',description:'The people who make learning possible. Manage your teaching team.'},parents:{title:'Parents & guardians',singular:'guardian',description:'Keep family contacts organized and easy to find.'}}
export default function DirectoryPage({kind}:{kind:Kind}){
 const meta=labels[kind],cache=useQueryClient(),schoolId=useAuthStore(s=>s.user?.schoolId)
 // Principals read the directory; only the school administrator may change it (the API enforces the same).
 const canEdit=isAdministrator(roleOf(useAuthStore(s=>s.user)))
 const [page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState('')
 const [editing,setEditing]=useState<Person|null|undefined>(),[removing,setRemoving]=useState<Person|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setPage(1)},250);return()=>clearTimeout(timer)},[search])
 const list=useQuery<{data:Person[],totalCount:number}>({queryKey:['directory',kind,page,query],queryFn:async()=>(await client.get('/operations/directory/'+kind,{params:{page,search:query}})).data.data})
 async function save(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setError('')
  const form=Object.fromEntries(new FormData(e.currentTarget).entries())
  const payload={...form,schoolId,id:editing?.id,dateOfBirth:form.dateOfBirth?String(form.dateOfBirth)+'T00:00:00Z':undefined}
  try{if(editing)await client.put('/'+kind+'/'+editing.id,payload);else await client.post('/'+kind,payload);setEditing(undefined);setNotice(meta.singular+' saved successfully.');await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}
 }
 async function remove(){if(!removing)return;setBusy(true);setError('');try{await client.delete('/'+kind+'/'+removing.id);setRemoving(null);setNotice('Record archived.');if(list.data?.data.length===1&&page>1)setPage(page-1);await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const common=[['firstName','First name','text',true,100],['lastName','Last name','text',true,100],['email','Email address','email',true,255],['phoneNumber','Phone number','tel',kind==='parents',20]] as const
 return <><PageHeader eyebrow="PEOPLE & COMMUNITY" title={meta.title} description={canEdit?meta.description:'View-only directory. Changes are made by the school administrator.'}>{canEdit&&<button className="button primary" onClick={()=>{setError('');setEditing(null)}}><Plus size={17}/>Add {meta.singular}</button>}</PageHeader>
 {notice&&<div className="success-box" role="status">{notice}</div>}
 <section className="panel directory-panel"><div className="directory-toolbar"><div className="directory-title"><span className="stat-icon teal"><Users size={20}/></span><div><h2>{meta.title} directory <span className="count-badge">{list.data?.totalCount??'—'}</span></h2><p>Search, update, and stay connected.</p></div></div><div className="toolbar-actions"><div className="search-field"><Search size={17}/><input aria-label="Search directory" value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="Search name or email…"/></div><button className="button secondary" disabled={!list.data?.data.length} onClick={()=>exportCsv(kind+'-page-'+page,list.data!.data as unknown as Record<string,unknown>[],[['First name','firstName'],['Last name','lastName'],['Email','email'],['Phone','phoneNumber'],...(kind==='students'?[['Class','currentClass'],['Roll number','rollNumber']] as [string,string][]:kind==='teachers'?[['Department','department']] as [string,string][]:[])])}><Download size={16}/>Export page</button></div></div>
 {list.isError?<ErrorBox message={errorMessage(list.error)}/>:list.isPending?<Loading/>:list.data.data.length===0?<Empty title={query?'No matching records':'Your community starts here'} description={query?'Try another name or email address.':'Add your first '+meta.singular+' to start building your directory.'}/>:<div className="table-scroll"><table><thead><tr><th>Name</th><th>{kind==='students'?'Roll number':kind==='teachers'?'Employee code':'Phone number'}</th><th>{kind==='students'?'Class':kind==='teachers'?'Department':'Email address'}</th>{kind!=='parents'&&<th>Status</th>}{(canEdit||kind==='students')&&<th className="align-right">Actions</th>}</tr></thead><tbody>{list.data.data.map((person,i)=><tr key={person.id}><td><div className="person-cell"><span className={'person-avatar tone-'+i%4}>{person.firstName[0]}{person.lastName[0]}</span><div><strong>{person.firstName} {person.lastName}</strong><small>{kind==='parents'?'Parent / guardian':person.email}</small></div></div></td><td>{kind==='students'?person.rollNumber:kind==='teachers'?person.employeeCode:person.phoneNumber||'—'}</td><td>{kind==='students'?<span className="class-tag">{person.currentClass}</span>:kind==='teachers'?person.department:person.email}</td>{kind!=='parents'&&<td><span className={'status-tag '+(person.status==='Active'?'active':'')}>{person.status}</span></td>}{(canEdit||kind==='students')&&<td><div className="row-actions">{kind==='students'&&<Link className="button small secondary" to={'/student360/'+person.id} aria-label={'Student 360 for '+person.firstName+' '+person.lastName}>360</Link>}{canEdit&&<><button className="icon-button" aria-label={'Edit '+person.firstName+' '+person.lastName} onClick={()=>{setError('');setEditing(person)}}><Pencil size={16}/></button><button className="icon-button danger-text" aria-label={'Archive '+person.firstName+' '+person.lastName} onClick={()=>{setError('');setRemoving(person)}}><Archive size={16}/></button></>}</div></td>}</tr>)}</tbody></table></div>}
 <Pagination page={page} total={list.data?.totalCount||0} onChange={setPage}/></section>
 <p className="page-note">Records belong to your school workspace. Archived records are preserved in the database and excluded from the active directory.</p>
 {editing!==undefined&&<Dialog title={(editing?'Edit ':'Add ')+meta.singular} onClose={()=>!busy&&setEditing(undefined)}><form onSubmit={save}>{error&&<ErrorBox message={error}/>}<div className="form-grid">{common.map(([key,label,type,required,max])=><label key={key}>{label}{!required&&<span className="optional"> (optional)</span>}<input name={key} type={type} required={required} maxLength={max} defaultValue={editing?.[key]||''}/></label>)}
 {kind==='students'&&<><label>Roll number<input name="rollNumber" required maxLength={50} defaultValue={editing?.rollNumber||''} readOnly={!!editing}/></label><label>Class / section<input name="currentClass" required maxLength={50} placeholder="e.g. Grade 6 - A" defaultValue={editing?.currentClass||''}/></label><label>Date of birth<input name="dateOfBirth" type="date" required max={today()} defaultValue={editing?.dateOfBirth?.slice(0,10)||''}/></label></>}
 {kind==='teachers'&&<><label>Employee code<input name="employeeCode" required maxLength={50} defaultValue={editing?.employeeCode||''} readOnly={!!editing}/></label><label>Department<input name="department" required maxLength={50} placeholder="e.g. Mathematics" defaultValue={editing?.department||''}/></label></>}
 {editing&&kind!=='parents'&&<label>Status<select name="status" defaultValue={editing.status||'Active'}><option>Active</option><option>Inactive</option><option>{kind==='students'?'Graduated':'Retired'}</option></select></label>}</div><div className="modal-footer"><button type="button" className="button secondary" disabled={busy} onClick={()=>setEditing(undefined)}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':'Save '+meta.singular}</button></div></form></Dialog>}
 {removing&&<Dialog title={'Archive '+meta.singular+'?'} onClose={()=>!busy&&setRemoving(null)}><p className="modal-copy">{removing.firstName} {removing.lastName} will be removed from the active directory. The record and its activity history will be preserved.</p>{error&&<ErrorBox message={error}/>}<div className="modal-footer"><button className="button secondary" disabled={busy} onClick={()=>setRemoving(null)}>Cancel</button><button className="button danger" disabled={busy} onClick={remove}>{busy?'Archiving…':'Archive record'}</button></div></Dialog>}</>
}
