import { FormEvent, useEffect, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Save, Download, Megaphone, Trash2, ShieldCheck } from 'lucide-react'
import client, { errorMessage } from '../api/client'
import { useAuthStore } from '../store/auth'
import { Dialog, Empty, ErrorBox, Loading, PageHeader, Pagination, exportCsv, today } from '../components/UI'
import type { Person } from './DirectoryPage'
type Page<T>={data:T[],totalCount:number}
type Notice={id:string,title:string,body:string,priority:string,createdAt:string}
export function AttendancePage(){
 const cache=useQueryClient(),[day,setDay]=useState(today()),[className,setClass]=useState(''),[page,setPage]=useState(1)
 const [draft,setDraft]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const dirty=Object.keys(draft).length>0
 const list=useQuery<Page<Person>>({queryKey:['attendance',day,className,page],queryFn:async()=>(await client.get('/operations/attendance',{params:{day,className,page}})).data.data})
 const overview=useQuery<{classes:{name:string}[]}>({queryKey:['overview',day],queryFn:async()=>(await client.get('/operations/overview',{params:{day}})).data.data})
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
 useEffect(()=>{const guard=(event:MouseEvent)=>{if(!dirty)return;const anchor=(event.target as Element)?.closest('a[href]');if(anchor && !window.confirm('Discard unsaved attendance changes?')){event.preventDefault();event.stopPropagation()}};document.addEventListener('click',guard,true);return()=>document.removeEventListener('click',guard,true)},[dirty])
 function change(action:()=>void){if(dirty&&!window.confirm('Discard unsaved attendance changes?'))return;setDraft({});setMessage('');setError('');action()}
 async function save(){setBusy(true);setError('');try{await client.post('/operations/attendance',{day,entries:Object.entries(draft).map(([studentId,status])=>({studentId,status}))});setDraft({});setMessage('Attendance saved successfully.');await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <><PageHeader eyebrow="THE DAILY RHYTHM" title="Attendance" description="Every student counts. Take a clear, reliable register for your school."><button className="button primary" disabled={!dirty||busy} onClick={save}><Save size={17}/>{busy?'Saving…':'Save attendance'}</button></PageHeader>
 {error&&<ErrorBox message={error}/>} {message&&<div className="success-box" role="status">{message}</div>}
 <section className="panel"><div className="attendance-toolbar"><label>Register date<input type="date" value={day} min="2000-01-01" max={today()} onChange={e=>e.target.value&&change(()=>{setDay(e.target.value);setPage(1)})}/></label><label>Class / section<select value={className} onChange={e=>change(()=>{setClass(e.target.value);setPage(1)})}><option value="">All classes</option>{overview.data?.classes.map(c=><option key={c.name}>{c.name}</option>)}</select></label><div className="attendance-toolbar-actions"><button className="button secondary" disabled={!list.data?.data.length||busy} onClick={()=>setDraft(Object.fromEntries(list.data!.data.map(p=>[p.id,'Present'])))}>Mark this page present</button><button className="button secondary" disabled={!list.data?.data.length||dirty} onClick={()=>exportCsv('attendance-'+day,list.data!.data as unknown as Record<string,unknown>[],[['Roll number','rollNumber'],['First name','firstName'],['Last name','lastName'],['Class','currentClass'],['Status','status']])}><Download size={16}/>Export page</button></div></div>
 <div className="register-note"><span className="dot teal-dot"/>{dirty?Object.keys(draft).length+' unsaved changes':'Changes are saved only when you select Save attendance.'}</div>
 {list.isError?<ErrorBox message={errorMessage(list.error)}/>:list.isPending?<Loading/>:!list.data.data.length?<Empty title="No active students in this register" description="Add active students to a class to start taking attendance."/>:<div className="table-scroll"><table><thead><tr><th>Student</th><th>Roll number</th><th>Class</th><th>Attendance status</th></tr></thead><tbody>{list.data.data.map(p=><tr key={p.id}><td><strong>{p.firstName} {p.lastName}</strong></td><td>{p.rollNumber}</td><td><span className="class-tag">{p.currentClass}</span></td><td><select className={'attendance-select '+((draft[p.id]||p.status||'')==='Present'?'present':'')} aria-label={'Attendance for '+p.firstName+' '+p.lastName} value={draft[p.id]||p.status||''} disabled={busy} onChange={e=>{setMessage('');setDraft({...draft,[p.id]:e.target.value})}}><option value="" disabled>Unmarked</option>{['Present','Absent','Late','Excused'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>}
 <Pagination page={page} size={100} total={list.data?.totalCount||0} onChange={n=>change(()=>setPage(n))}/></section></>
}
export function AnnouncementsPage(){
 const cache=useQueryClient(),[open,setOpen]=useState(false),[removing,setRemoving]=useState<Notice|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const list=useQuery<Notice[]>({queryKey:['announcements'],queryFn:async()=>(await client.get('/operations/announcements')).data.data})
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{await client.post('/operations/announcements',f);setOpen(false);await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function remove(){if(!removing)return;setBusy(true);try{await client.delete('/operations/announcements/'+removing.id);setRemoving(null);await cache.invalidateQueries()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <><PageHeader eyebrow="KEEP EVERYONE CONNECTED" title="School noticeboard" description="A shared space for updates, reminders, and the moments that matter to your administration team."><button className="button primary" onClick={()=>{setError('');setOpen(true)}}><Plus size={17}/>New announcement</button></PageHeader>
 {list.isError?<ErrorBox message={errorMessage(list.error)}/>:list.isPending?<Loading/>:!list.data.length?<section className="panel"><Empty title="Your next school update belongs here" description="Create an announcement to share with your school's administrators."/></section>:<div className="announcements-grid">{list.data.map(n=><article className="panel announcement-card" key={n.id}><div className="announcement-top"><span className={'stat-icon '+(n.priority==='Important'?'peach':'teal')}><Megaphone size={21}/></span><span className={'status-tag '+(n.priority==='Important'?'important':'')}>{n.priority}</span><button className="icon-button" aria-label={'Remove '+n.title} onClick={()=>{setError('');setRemoving(n)}}><Trash2 size={16}/></button></div><h2>{n.title}</h2><p>{n.body}</p><footer>{new Date(n.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})} · School administration</footer></article>)}</div>}
 {open&&<Dialog title="New announcement" onClose={()=>!busy&&setOpen(false)}><form onSubmit={save}>{error&&<ErrorBox message={error}/>}<div className="form-stack"><label>Title<input name="title" required maxLength={150} placeholder="What would you like to share?"/></label><label>Message<textarea name="body" required maxLength={4000} rows={6} placeholder="Add the details your team needs…"/></label><label>Priority<select name="priority"><option>Normal</option><option>Important</option></select></label></div><div className="modal-footer"><button type="button" className="button secondary" onClick={()=>setOpen(false)} disabled={busy}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Publishing…':'Publish announcement'}</button></div></form></Dialog>}
 {removing&&<Dialog title="Remove announcement?" onClose={()=>!busy&&setRemoving(null)}><p className="modal-copy">“{removing.title}” will be removed from the noticeboard. The removal is recorded in the activity log.</p>{error&&<ErrorBox message={error}/>}<div className="modal-footer"><button className="button secondary" disabled={busy} onClick={()=>setRemoving(null)}>Cancel</button><button className="button danger" disabled={busy} onClick={remove}>Remove announcement</button></div></Dialog>}</>
}
type Audit={id:string,action:string,entityType:string,entityId:string,timestamp:string}
export function AuditPage(){
 const [page,setPage]=useState(1)
 const list=useQuery<Page<Audit>>({queryKey:['audit',page],queryFn:async()=>(await client.get('/operations/audit',{params:{page}})).data.data})
 return <><PageHeader eyebrow="VISIBILITY & ACCOUNTABILITY" title="Activity log" description="A chronological record of database changes within your school workspace."><button className="button secondary" disabled={!list.data?.data.length} onClick={()=>exportCsv('activity-page-'+page,list.data!.data as unknown as Record<string,unknown>[],[['Time','timestamp'],['Action','action'],['Area','entityType'],['Record','entityId']])}><Download size={16}/>Export page</button></PageHeader><div className="info-box"><ShieldCheck size={20}/><span>Change events are recorded automatically. This log shows the operation and affected record; it does not identify the staff member who made the change.</span></div><section className="panel">
 {list.isError?<ErrorBox message={errorMessage(list.error)}/>:list.isPending?<Loading/>:!list.data.data.length?<Empty title="Your school history starts here" description="Saved records and updates will appear automatically."/>:<div className="table-scroll"><table><thead><tr><th>Time</th><th>Action</th><th>Area</th><th>Record ID</th></tr></thead><tbody>{list.data.data.map(a=><tr key={a.id}><td>{new Date(a.timestamp).toLocaleString()}</td><td><span className={'status-tag '+(a.action==='INSERT'?'active':'')}>{a.action==='INSERT'?'Created':a.action==='UPDATE'?'Updated':'Removed'}</span></td><td className="capitalize">{a.entityType.replaceAll('_',' ')}</td><td><code className="record-id">{a.entityId}</code></td></tr>)}</tbody></table></div>}<Pagination page={page} size={50} total={list.data?.totalCount||0} onChange={setPage}/></section></>
}
type Account={id:string,username:string,email:string,firstName:string,lastName:string,isActive:boolean,role:string}
export function SettingsPage(){
 const schoolId=useAuthStore(s=>s.user?.schoolId),currentId=useAuthStore(s=>s.user?.id),cache=useQueryClient()
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[page,setPage]=useState(1)
 const school=useQuery({queryKey:['school',schoolId],queryFn:async()=>(await client.get('/schools/'+schoolId)).data.data})
 const roles=useQuery<{id:string,name:string}[]>({queryKey:['roles'],queryFn:async()=>(await client.get('/roles')).data.data})
 const users=useQuery<Page<Account>>({queryKey:['users',page],queryFn:async()=>(await client.get('/users',{params:{page,pageSize:20}})).data.data})
 async function saveSchool(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await client.put('/schools/'+schoolId,Object.fromEntries(new FormData(e.currentTarget)));setMessage('School profile saved.');await cache.invalidateQueries({queryKey:['school']})}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function saveUser(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await client.post('/users',{...Object.fromEntries(new FormData(e.currentTarget)),schoolId});setOpen(false);setMessage('Staff account created. Share credentials with the staff member securely.');await cache.invalidateQueries({queryKey:['users']})}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function toggle(u:Account){if(!window.confirm((u.isActive?'Disable':'Enable')+' access for '+u.username+'?'))return;setBusy(true);setError('');try{await client.put('/users/'+u.id,{isActive:!u.isActive});await cache.invalidateQueries({queryKey:['users']});setMessage('Staff access updated.')}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <><PageHeader eyebrow="MAKE IT YOUR OWN" title="School settings" description="Manage your school identity and who can access your administration workspace."/>
 {error&&!open&&<ErrorBox message={error}/>} {message&&<div className="success-box" role="status">{message}</div>}
 <div className="settings-grid"><section className="panel settings-profile"><div className="panel-heading"><div><h2>School profile</h2><p>The details that make this workspace yours.</p></div></div>{school.isPending?<Loading/>:school.isError?<ErrorBox message={errorMessage(school.error)}/>:<form onSubmit={saveSchool} className="form-stack"><label>School name<input name="name" required maxLength={255} defaultValue={school.data.name}/></label><label>Principal name<input name="principalName" maxLength={255} defaultValue={school.data.principalName||''}/></label><label>School ID<input readOnly value={schoolId}/></label><button className="button primary" disabled={busy}><Save size={16}/>Save profile</button></form>}</section><section className="panel settings-note"><span className="stat-icon teal"><ShieldCheck size={24}/></span><h2>A dedicated workspace</h2><p>Your directories, attendance, notices, and history are scoped to your school.</p><ul><li>Signed access tokens and school scope checks</li><li>Administrator and principal access</li><li>Database change history</li><li>Persistent local database storage</li></ul><p className="muted">Both built-in roles manage school administration. Student and parent self-service portals are not enabled.</p></section></div>
 <section className="panel directory-panel"><div className="directory-toolbar"><div><h2>Staff access</h2><p>Give trusted staff access to your school workspace.</p></div><button className="button primary" onClick={()=>{setError('');setOpen(true)}}><Plus size={16}/>Add staff account</button></div>{users.isPending?<Loading/>:users.isError?<ErrorBox message={errorMessage(users.error)}/>:<div className="table-scroll"><table><thead><tr><th>Staff member</th><th>Username</th><th>Role</th><th>Access</th><th>Action</th></tr></thead><tbody>{users.data.data.map(u=><tr key={u.id}><td><strong>{u.firstName} {u.lastName}</strong><small className="cell-small">{u.email}</small></td><td>{u.username}</td><td>{u.role}</td><td><span className={'status-tag '+(u.isActive?'active':'')}>{u.isActive?'Enabled':'Disabled'}</span></td><td>{u.id===currentId?<span className="muted">Your account</span>:<button className="button small secondary" disabled={busy} onClick={()=>toggle(u)}>{u.isActive?'Disable':'Enable'}</button>}</td></tr>)}</tbody></table></div>}<Pagination page={page} total={users.data?.totalCount||0} onChange={setPage}/></section>
 {open&&<Dialog title="Add staff account" onClose={()=>!busy&&setOpen(false)}><form onSubmit={saveUser}>{error&&<ErrorBox message={error}/>}<div className="form-grid"><label>First name<input name="firstName" required maxLength={100}/></label><label>Last name<input name="lastName" required maxLength={100}/></label><label>Username<input name="username" required maxLength={100} autoComplete="off"/></label><label>Email address<input name="email" type="email" required maxLength={255}/></label><label className="full-width">Password<input name="password" type="password" required minLength={16} maxLength={72} autoComplete="new-password"/><small>Use 16–72 characters. Share it privately with this staff member.</small></label><label className="full-width">Role<select name="roleId" required><option value="">Select a role</option>{roles.data?.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label></div>{roles.isError&&<ErrorBox message={errorMessage(roles.error)}/>}<div className="modal-footer"><button className="button secondary" type="button" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="button primary" disabled={busy||!roles.data?.length}>{busy?'Creating…':'Create account'}</button></div></form></Dialog>}</>
}
