import { FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import client, { errorMessage } from '../api/client'
import { ErrorBox } from '../components/UI'
export default function SignupPage(){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await client.post('/auth/signup',Object.fromEntries(new FormData(e.currentTarget)));setDone(true)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <main className="login-form-side" style={{minHeight:'100vh'}}><section className="login-form-wrap"><span className="eyebrow">EDUOS</span><h1>Create account</h1><p>Request access to your school. Your administrator will verify your details and assign an approved role.</p>{error&&<ErrorBox message={error}/>} {done?<div role="status" className="success-box">Your access request has been submitted to the school administrator for approval.</div>:<form onSubmit={submit}><label>First name<input name="firstName" required maxLength={100} autoComplete="given-name"/></label><label>Last name<input name="lastName" required maxLength={100} autoComplete="family-name"/></label><label>Email<input name="email" type="email" required maxLength={255} autoComplete="email"/></label><label>Mobile<input name="phone" type="tel" maxLength={20} required autoComplete="tel"/></label><label>School code<input name="schoolCode" required maxLength={64}/></label><label>Requested account type<select name="requestedRole">{['Teacher','Principal','Parent','Student','School Staff'].map(r=><option key={r}>{r}</option>)}</select></label><label>Password<input name="password" type="password" required minLength={16} maxLength={72} autoComplete="new-password"/></label><button className="button primary" disabled={busy}>{busy?'Submitting…':'Submit request'}</button></form>}<p><Link to="/login">Sign in</Link></p></section></main>
}
